"use client";
import { FormEvent, useState } from "react";

export type Claim={id:string;covered_person:string;policy_name:string;claim_type:string;claims_contact?:string;hotline?:string;email?:string;required_documents?:string;reference_number?:string;submission_date?:string;status:string;follow_up_date?:string;responsible_person?:string;notes?:string};
export type DocumentRecord={id:string;name:string;category:string;original_location?:string;expiry_date?:string;linked_record_type?:string;status:string;last_confirmed_at?:string;next_review_date?:string;information_source?:string};
export type Professional={id:string;name:string;organisation?:string;category:string;registration_details?:string;location?:string;languages?:string;telephone?:string;whatsapp?:string;email?:string;website?:string;matters_handled?:string;emergency_contact_permission?:boolean;application_status:string;licence_expiry?:string;referral_disclosure?:string;is_directory_demo:boolean};
type Save=(table:string,data:Record<string,unknown>)=>Promise<void>;type Update=(table:string,id:string,data:Record<string,unknown>)=>Promise<void>;type Remove=(table:string,id:string)=>Promise<void>;
const formatDate=(v?:string)=>v?new Intl.DateTimeFormat("en-MY",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v+"T00:00:00")):"Not set";

const claimFields:[string,string,string?][]=[["covered_person","Covered person"],["policy_name","Policy / certificate"],["claim_type","Claim type"],["claims_contact","Claims contact"],["hotline","Hotline"],["email","Email","email"],["required_documents","Required-document checklist"],["reference_number","Claim reference"],["submission_date","Submission date","date"],["status","Status"],["follow_up_date","Follow-up date","date"],["responsible_person","Responsible family member"],["notes","Notes"]];
export function ClaimsCentre({records,save,update,remove}:{records:Claim[];save:Save;update:Update;remove:Remove}){const [open,setOpen]=useState(false),[editing,setEditing]=useState<Claim|null>(null),[query,setQuery]=useState(""),[status,setStatus]=useState("all");const shown=records.filter(r=>(status==="all"||r.status===status)&&`${r.covered_person} ${r.policy_name} ${r.claim_type} ${r.reference_number||""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.follow_up_date||"9999").localeCompare(b.follow_up_date||"9999"));return <><PageTitle eyebrow="CLAIMS CENTRE" title="Keep every claim follow-up clear" copy="Record claim facts, required documents, reference numbers and the family member responsible." add={()=>setOpen(true)} label="Add claim"/><SearchTools query={query} setQuery={setQuery} value={status} setValue={setStatus} options={["all",...new Set(records.map(r=>r.status))]}/><section className="panel records">{shown.length?shown.map(r=><article className="operation-card" key={r.id}><div><span className="pill">{r.status}</span><h3>{r.covered_person} · {r.claim_type}</h3><p>{r.policy_name} · Follow-up {formatDate(r.follow_up_date)}</p><small>{r.claims_contact||"Claims contact missing"} {r.reference_number&&`· Ref ${r.reference_number}`}</small></div><CardActions edit={()=>setEditing(r)} remove={()=>remove("claims",r.id)}/></article>):<Empty text="No matching claims." add={()=>setOpen(true)}/>}</section><p className="disclaimer">Claim records organise information only. Vitala Amanah does not determine eligibility, coverage or approval.</p>{open&&<DataModal title="Add a claim" table="claims" fields={claimFields} close={()=>setOpen(false)} save={save}/>} {editing&&<DataModal title="Edit claim" table="claims" id={editing.id} initial={editing as unknown as Record<string,unknown>} fields={claimFields} close={()=>setEditing(null)} save={save} update={update}/>}</>}

const documentFields:[string,string,string?][]=[["name","Document name"],["category","Category"],["original_location","Original document location"],["expiry_date","Expiry date","date"],["linked_record_type","Linked asset / policy / record"],["status","Status"],["next_review_date","Next review date","date"],["information_source","Information source"]];
export function Documents({records,save,update,remove}:{records:DocumentRecord[];save:Save;update:Update;remove:Remove}){const [open,setOpen]=useState(false),[editing,setEditing]=useState<DocumentRecord|null>(null),[query,setQuery]=useState(""),[category,setCategory]=useState("all");const shown=records.filter(r=>(category==="all"||r.category===category)&&`${r.name} ${r.category} ${r.original_location||""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.expiry_date||"9999").localeCompare(b.expiry_date||"9999"));return <><PageTitle eyebrow="DOCUMENTS" title="Document register" copy="Track where originals are kept, expiry dates and linked records without uploading sensitive files." add={()=>setOpen(true)} label="Add document"/><SearchTools query={query} setQuery={setQuery} value={category} setValue={setCategory} options={["all",...new Set(records.map(r=>r.category))]}/><section className="panel records">{shown.length?shown.map(r=>{const expired=!!r.expiry_date&&new Date(r.expiry_date)<new Date();return <article className="operation-card" key={r.id}><div><span className={expired?"pill amber":"pill"}>{expired?"Expired":r.status}</span><h3>{r.name}</h3><p>{r.category} · Expires {formatDate(r.expiry_date)}</p><small>Original: {r.original_location||"Location not recorded"} · {r.linked_record_type||"Not linked"}</small></div><CardActions edit={()=>setEditing(r)} remove={()=>remove("document_records",r.id)}/></article>}):<Empty text="No matching document metadata." add={()=>setOpen(true)}/>}</section><p className="disclaimer">Metadata only. Real uploads remain disabled until client-side encryption and recovery architecture pass independent security review.</p>{open&&<DataModal title="Add document metadata" table="document_records" fields={documentFields} close={()=>setOpen(false)} save={save}/>} {editing&&<DataModal title="Edit document metadata" table="document_records" id={editing.id} initial={editing as unknown as Record<string,unknown>} fields={documentFields} close={()=>setEditing(null)} save={save} update={update}/>}</>}

const professionalFields:[string,string,string?][]=[["name","Full name"],["organisation","Organisation"],["category","Professional category"],["registration_details","Registration / licence details"],["location","Location"],["languages","Languages"],["telephone","Telephone"],["whatsapp","WhatsApp"],["email","Email","email"],["website","Website","url"],["matters_handled","Matters handled"],["licence_expiry","Licence expiry","date"],["notes","Notes"]];
export function Professionals({records,save,update,remove}:{records:Professional[];save:Save;update:Update;remove:Remove}){const [open,setOpen]=useState(false),[editing,setEditing]=useState<Professional|null>(null),[query,setQuery]=useState(""),[category,setCategory]=useState("all");const match=(r:Professional)=>(category==="all"||r.category===category)&&`${r.name} ${r.organisation||""} ${r.location||""} ${r.languages||""}`.toLowerCase().includes(query.toLowerCase()),mine=records.filter(r=>!r.is_directory_demo&&match(r)),directory=records.filter(r=>r.is_directory_demo&&match(r));return <><PageTitle eyebrow="PROFESSIONALS" title="People who can help" copy="Keep private professional contacts separate from Vitala's fictional demonstration directory." add={()=>setOpen(true)} label="Add my professional"/><SearchTools query={query} setQuery={setQuery} value={category} setValue={setCategory} options={["all",...new Set(records.map(r=>r.category))]}/><section className="panel records"><div className="panel-head"><h2>My professionals</h2></div>{mine.length?mine.map(r=><ProCard key={r.id} item={r} edit={()=>setEditing(r)} remove={()=>remove("professionals",r.id)}/>):<Empty text="No matching private professionals." add={()=>setOpen(true)}/>}</section><section className="panel records"><div className="panel-head"><h2>Vitala Professional Directory</h2><span className="pill amber">Demo profiles</span></div>{directory.map(r=><ProCard key={r.id} item={r}/>)}</section><p className="disclaimer">All directory profiles shown here are fictional demonstrations, not verified recommendations. Private contacts never become public automatically.</p>{open&&<DataModal title="Add my professional" table="professionals" fields={professionalFields} defaults={{application_status:"Private",is_directory_demo:false}} close={()=>setOpen(false)} save={save}/>} {editing&&<DataModal title="Edit my professional" table="professionals" id={editing.id} initial={editing as unknown as Record<string,unknown>} fields={professionalFields} close={()=>setEditing(null)} save={save} update={update}/>}</>}
function ProCard({item:r,edit,remove}:{item:Professional;edit?:()=>void;remove?:()=>void}){return <article className="operation-card"><div><span className={r.is_directory_demo?"pill amber":"pill"}>{r.is_directory_demo?"Demo":r.application_status}</span><h3>{r.name}</h3><p>{r.category} · {r.organisation||"Independent"} · {r.location||"Location not set"}</p><small>{r.languages||"Languages not recorded"} {r.telephone&&`· ${r.telephone}`}</small></div>{remove&&<CardActions edit={edit!} remove={remove}/>}</article>}
function PageTitle({eyebrow,title,copy,add,label}:{eyebrow:string;title:string;copy:string;add:()=>void;label:string}){return <div className="title-row"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div><button className="primary" onClick={add}>＋ {label}</button></div>}
function Empty({text,add}:{text:string;add:()=>void}){return <div className="empty"><b>{text}</b><button className="secondary" onClick={add}>Add the first record</button></div>}
function SearchTools({query,setQuery,value,setValue,options}:{query:string;setQuery:(v:string)=>void;value:string;setValue:(v:string)=>void;options:string[]}){return <div className="record-tools"><label><span className="sr-only">Search records</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records…"/></label><label><span className="sr-only">Filter records</span><select value={value} onChange={e=>setValue(e.target.value)}>{options.map(x=><option key={x} value={x}>{x==="all"?"All categories / statuses":x}</option>)}</select></label></div>}
function CardActions({edit,remove}:{edit:()=>void;remove:()=>void}){return <div className="card-actions"><button className="secondary" onClick={edit}>Edit</button><button className="delete" onClick={remove}>×</button></div>}
function DataModal({title,table,id,fields,defaults={},initial={},close,save,update}:{title:string;table:string;id?:string;fields:[string,string,string?][];defaults?:Record<string,unknown>;initial?:Record<string,unknown>;close:()=>void;save:Save;update?:Update}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data={...defaults,...Object.fromEntries(new FormData(e.currentTarget))};if(id&&update)await update(table,id,data);else await save(table,data);close()}return <div className="modal-wrap"><form className="modal" onSubmit={submit}><div className="panel-head"><h2>{title}</h2><button type="button" className="close" onClick={close}>×</button></div>{fields.map(([name,label,type])=><label key={name}>{label}<input name={name} type={type||"text"} defaultValue={String(initial[name]??"")} required={["name","category","covered_person","policy_name","claim_type","status"].includes(name)}/></label>)}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">{id?"Save changes":"Save"}</button></div></form></div>}
