"use client";
import { FormEvent, useState } from "react";

export type Claim={id:string;covered_person:string;policy_name:string;claim_type:string;claims_contact?:string;hotline?:string;email?:string;required_documents?:string;reference_number?:string;submission_date?:string;status:string;follow_up_date?:string;responsible_person?:string;notes?:string};
export type DocumentRecord={id:string;name:string;category:string;original_location?:string;expiry_date?:string;linked_record_type?:string;status:string;last_confirmed_at?:string;next_review_date?:string;information_source?:string};
export type Professional={id:string;name:string;organisation?:string;category:string;registration_details?:string;location?:string;languages?:string;telephone?:string;whatsapp?:string;email?:string;website?:string;matters_handled?:string;emergency_contact_permission?:boolean;application_status:string;licence_expiry?:string;referral_disclosure?:string;is_directory_demo:boolean};
type Save=(table:string,data:Record<string,unknown>)=>Promise<void>;type Remove=(table:string,id:string)=>Promise<void>;
const formatDate=(v?:string)=>v?new Intl.DateTimeFormat("en-MY",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v+"T00:00:00")):"Not set";

export function ClaimsCentre({records,save,remove}:{records:Claim[];save:Save;remove:Remove}){const [open,setOpen]=useState(false);return <><PageTitle eyebrow="CLAIMS CENTRE" title="Keep every claim follow-up clear" copy="Record claim facts, required documents, reference numbers and the family member responsible." add={()=>setOpen(true)} label="Add claim"/><section className="panel records">{records.length?records.map(r=><article className="operation-card" key={r.id}><div><span className="pill">{r.status}</span><h3>{r.covered_person} · {r.claim_type}</h3><p>{r.policy_name} · Follow-up {formatDate(r.follow_up_date)}</p><small>{r.claims_contact||"Claims contact missing"} {r.reference_number&&`· Ref ${r.reference_number}`}</small></div><button className="delete" onClick={()=>remove("claims",r.id)}>×</button></article>):<Empty text="No claims recorded." add={()=>setOpen(true)}/>}</section><p className="disclaimer">Claim records organise information only. Vitala Amanah does not determine eligibility, coverage or approval.</p>{open&&<DataModal title="Add a claim" table="claims" fields={[["covered_person","Covered person"],["policy_name","Policy / certificate"],["claim_type","Claim type"],["claims_contact","Claims contact"],["hotline","Hotline"],["email","Email","email"],["required_documents","Required-document checklist"],["reference_number","Claim reference"],["submission_date","Submission date","date"],["status","Status"],["follow_up_date","Follow-up date","date"],["responsible_person","Responsible family member"],["notes","Notes"]]} close={()=>setOpen(false)} save={save}/>}</>}

export function Documents({records,save,remove}:{records:DocumentRecord[];save:Save;remove:Remove}){const [open,setOpen]=useState(false);return <><PageTitle eyebrow="DOCUMENTS" title="Document register" copy="Track where originals are kept, expiry dates and linked records without uploading sensitive files." add={()=>setOpen(true)} label="Add document"/><section className="panel records">{records.length?records.map(r=>{const expired=!!r.expiry_date&&new Date(r.expiry_date)<new Date();return <article className="operation-card" key={r.id}><div><span className={expired?"pill amber":"pill"}>{expired?"Expired":r.status}</span><h3>{r.name}</h3><p>{r.category} · Expires {formatDate(r.expiry_date)}</p><small>Original: {r.original_location||"Location not recorded"} · {r.linked_record_type||"Not linked"}</small></div><button className="delete" onClick={()=>remove("document_records",r.id)}>×</button></article>}):<Empty text="No document metadata recorded." add={()=>setOpen(true)}/>}</section><p className="disclaimer">Metadata only. Real uploads remain disabled until client-side encryption and recovery architecture pass independent security review.</p>{open&&<DataModal title="Add document metadata" table="document_records" fields={[["name","Document name"],["category","Category"],["original_location","Original document location"],["expiry_date","Expiry date","date"],["linked_record_type","Linked asset / policy / record"],["status","Status"],["next_review_date","Next review date","date"],["information_source","Information source"]]} close={()=>setOpen(false)} save={save}/>}</>}

export function Professionals({records,save,remove}:{records:Professional[];save:Save;remove:Remove}){const [open,setOpen]=useState(false),mine=records.filter(r=>!r.is_directory_demo),directory=records.filter(r=>r.is_directory_demo);return <><PageTitle eyebrow="PROFESSIONALS" title="People who can help" copy="Keep private professional contacts separate from Vitala's fictional demonstration directory." add={()=>setOpen(true)} label="Add my professional"/><section className="panel records"><div className="panel-head"><h2>My professionals</h2></div>{mine.length?mine.map(r=><ProCard key={r.id} item={r} remove={()=>remove("professionals",r.id)}/>):<Empty text="No private professionals yet." add={()=>setOpen(true)}/>}</section><section className="panel records"><div className="panel-head"><h2>Vitala Professional Directory</h2><span className="pill amber">Demo profiles</span></div>{directory.map(r=><ProCard key={r.id} item={r}/>)}</section><p className="disclaimer">All directory profiles shown here are fictional demonstrations, not verified recommendations. Private contacts never become public automatically.</p>{open&&<DataModal title="Add my professional" table="professionals" fields={[["name","Full name"],["organisation","Organisation"],["category","Professional category"],["registration_details","Registration / licence details"],["location","Location"],["languages","Languages"],["telephone","Telephone"],["whatsapp","WhatsApp"],["email","Email","email"],["website","Website","url"],["matters_handled","Matters handled"],["licence_expiry","Licence expiry","date"],["notes","Notes"]]} defaults={{application_status:"Private",is_directory_demo:false}} close={()=>setOpen(false)} save={save}/>}</>}
function ProCard({item:r,remove}:{item:Professional;remove?:()=>void}){return <article className="operation-card"><div><span className={r.is_directory_demo?"pill amber":"pill"}>{r.is_directory_demo?"Demo":r.application_status}</span><h3>{r.name}</h3><p>{r.category} · {r.organisation||"Independent"} · {r.location||"Location not set"}</p><small>{r.languages||"Languages not recorded"} {r.telephone&&`· ${r.telephone}`}</small></div>{remove&&<button className="delete" onClick={remove}>×</button>}</article>}
function PageTitle({eyebrow,title,copy,add,label}:{eyebrow:string;title:string;copy:string;add:()=>void;label:string}){return <div className="title-row"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div><button className="primary" onClick={add}>＋ {label}</button></div>}
function Empty({text,add}:{text:string;add:()=>void}){return <div className="empty"><b>{text}</b><button className="secondary" onClick={add}>Add the first record</button></div>}
function DataModal({title,table,fields,defaults={},close,save}:{title:string;table:string;fields:[string,string,string?][];defaults?:Record<string,unknown>;close:()=>void;save:Save}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data={...defaults,...Object.fromEntries(new FormData(e.currentTarget))};await save(table,data);close()}return <div className="modal-wrap"><form className="modal" onSubmit={submit}><div className="panel-head"><h2>{title}</h2><button type="button" className="close" onClick={close}>×</button></div>{fields.map(([name,label,type])=><label key={name}>{label}<input name={name} type={type||"text"} required={["name","category","covered_person","policy_name","claim_type","status"].includes(name)}/></label>)}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Save</button></div></form></div>}
