"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import PropertyModal from "./property-modal";
import { FamilyPack, type FamilyPackRecord } from "./family-pack";
import { VitalaGuide } from "./vitala-guide";
import { ClaimsCentre, Documents, Professionals, type Claim, type DocumentRecord, type Professional } from "./operations";
import { ReportsCentre } from "./reports-centre";

type Asset = { id:string; name:string; category:string; value:number; liquidity:string; institution:string|null; notes:string|null; address?:string; state?:string; property_type?:string; ownership_percentage?:number; joint_owner?:string; occupancy?:string; rental_income?:number; rental_manager?:string; rental_manager_contact?:string; tenancy_start?:string; tenancy_end?:string; tenancy_agreement_name?:string; tenancy_status?:string; loan_provider?:string; outstanding_loan?:number; monthly_instalment?:number; interest_rate?:number; loan_maturity?:string; maintenance_fee?:number; title_number?:string; tenure?:string; purchase_price?:number; purchase_date?:string };
type Liability = { id:string; name:string; category:string; balance:number; lender:string|null; monthly_payment:number };
type Policy = { id:string; provider:string; policy_type:string; masked_number:string|null; coverage:number; premium:number; renewal_date:string|null; status:string; claims_contact:string|null };
type Contact = { id:string; name:string; relationship:string; role:string; phone:string|null; email:string|null; emergency_access:boolean };
type Legacy = { id:string; title:string; record_type:string; status:string; professional:string|null; review_date:string|null; notes:string|null };
type Reminder = { id:string; title:string; due_date:string; category:string; completed:boolean };
type Retirement = { id:string; current_age:number; retirement_age:number; monthly_spending:number; current_savings:number; monthly_contribution:number; annual_return:number; inflation:number };
type Profile = { full_name:string|null; onboarding_complete:boolean };
type View = "home"|"wealth"|"protection"|"legacy"|"retirement"|"family"|"familyPack"|"claims"|"documents"|"professionals"|"guide"|"reports"|"reminders"|"settings";

const money = (n:number) => new Intl.NumberFormat("en-MY",{style:"currency",currency:"MYR",maximumFractionDigits:0}).format(n);
const date = (s:string|null) => s ? new Intl.DateTimeFormat("en-MY",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(s+"T00:00:00")) : "Not set";
const nav: {id:View; label:string; icon:string}[] = [
  {id:"home",label:"Home",icon:"⌂"},{id:"wealth",label:"My Wealth",icon:"◈"},{id:"protection",label:"Protection",icon:"◇"},
  {id:"legacy",label:"Legacy",icon:"✦"},{id:"retirement",label:"Retirement",icon:"◒"},{id:"family",label:"Family",icon:"♧"},
  {id:"familyPack",label:"Family Pack",icon:"▣"},
  {id:"claims",label:"Claims Centre",icon:"✓"},{id:"documents",label:"Documents",icon:"▤"},{id:"professionals",label:"Professionals",icon:"◎"},
  {id:"guide",label:"Vitala Guide",icon:"✧"},{id:"reports",label:"Reports",icon:"▧"},
  {id:"reminders",label:"Reminders",icon:"◷"},{id:"settings",label:"Settings",icon:"⚙"}
];

export default function Home(){
  const db=useMemo(()=>createClient(),[]); const [view,setView]=useState<View>("home"); const [menu,setMenu]=useState(false);
  const [account,setAccount]=useState<{id:string;email?:string}|null>(null);
  const [profile,setProfile]=useState<Profile|null>(null);
  const [assets,setAssets]=useState<Asset[]>([]),[liabilities,setLiabilities]=useState<Liability[]>([]),[policies,setPolicies]=useState<Policy[]>([]);
  const [contacts,setContacts]=useState<Contact[]>([]),[legacy,setLegacy]=useState<Legacy[]>([]),[reminders,setReminders]=useState<Reminder[]>([]),[retirement,setRetirement]=useState<Retirement|null>(null);
  const [familyPack,setFamilyPack]=useState<FamilyPackRecord|null>(null);
  const [claims,setClaims]=useState<Claim[]>([]),[documents,setDocuments]=useState<DocumentRecord[]>([]),[professionals,setProfessionals]=useState<Professional[]>([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState(""),[modal,setModal]=useState<string|null>(null),[notice,setNotice]=useState("");
  const [guideOpen,setGuideOpen]=useState(false);
  const load=useCallback(async()=>{ setLoading(true); setError(""); const names=["assets","liabilities","policies","contacts","legacy_records","reminders","retirement_profiles"] as const;
    const result=await Promise.all([...names.map(n=>db.from(n).select("*").order("created_at" in {} ? "created_at":"id")),db.from("family_packs").select("*").maybeSingle(),db.from("claims").select("*").is("deleted_at",null).order("created_at"),db.from("document_records").select("*").is("deleted_at",null).order("created_at"),db.from("professionals").select("*").is("deleted_at",null).order("created_at")]);
    const failed=result.find(r=>r.error); if(failed?.error){setError("The database schema is not ready yet. Apply the included Supabase migration, then refresh.");setLoading(false);return;}
    setAssets((result[0].data||[]) as Asset[]);setLiabilities((result[1].data||[]) as Liability[]);setPolicies((result[2].data||[]) as Policy[]);setContacts((result[3].data||[]) as Contact[]);setLegacy((result[4].data||[]) as Legacy[]);setReminders((result[5].data||[]) as Reminder[]);setRetirement((result[6].data?.[0]||null) as Retirement|null);setFamilyPack((result[7].data||null) as FamilyPackRecord|null);setClaims((result[8].data||[]) as Claim[]);setDocuments((result[9].data||[]) as DocumentRecord[]);setProfessionals((result[10].data||[]) as Professional[]);setLoading(false);
  },[db]);
  useEffect(()=>{load();db.auth.getUser().then(async({data})=>{setAccount(data.user);if(data.user){const {data:p}=await db.from("profiles").select("full_name,onboarding_complete").eq("id",data.user.id).maybeSingle();if(!p?.onboarding_complete||!p.full_name?.trim()){location.replace("/onboarding");return}setProfile(p as Profile)}});const {data:{subscription}}=db.auth.onAuthStateChange((_event,session)=>setAccount(session?.user||null));return()=>subscription.unsubscribe()},[load,db]);
  useEffect(()=>{if(!menu)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setMenu(false)};document.addEventListener("keydown",close);document.body.classList.add("drawer-open");return()=>{document.removeEventListener("keydown",close);document.body.classList.remove("drawer-open")}},[menu]);
  async function save(table:string, values:Record<string,unknown>){if(!account){location.href="/login";return}const owned={...values,owner_id:account.id,is_demo:account.email==="demo@vitala-amanah.app"};const {error:e}=await db.from(table).insert(owned);if(e){setNotice(`Could not save: ${e.message}`);return} await db.from("audit_events").insert({action:"created",entity_type:table,details:{name:values.name||values.title||values.provider},owner_id:account.id,is_demo:owned.is_demo});setModal(null);setNotice("Saved securely to your family organiser.");await load()}
  async function remove(table:string,id:string){if(!confirm("Delete this record? This removes it from your organiser."))return;await db.from(table).delete().eq("id",id);setNotice("Record deleted.");await load()}
  const totals=useMemo(()=>({assets:assets.reduce((a,x)=>a+Number(x.value),0),debts:liabilities.reduce((a,x)=>a+Number(x.balance),0),coverage:policies.reduce((a,x)=>a+Number(x.coverage),0)}),[assets,liabilities,policies]);
  const packProgress=Math.round((familyPack?.completed_sections?.length||0)/18*100);
  const score=(assets.length?15:0)+(liabilities.length?10:0)+(policies.length?15:0)+(legacy.some(l=>l.record_type.toLowerCase().includes("nomination")&&l.status!=="Needs review")?15:0)+(legacy.some(l=>/hibah|will|wasiat|trust/i.test(l.record_type)&&l.status!=="Needs review")?15:0)+(contacts.some(c=>c.emergency_access)?10:0)+(packProgress>=75?10:0)+(retirement?10:0);
  function go(v:View){setView(v);setMenu(false);setNotice("")}
  return <div className="shell">
    <aside className={menu?"sidebar open":"sidebar"} aria-label="Primary navigation"><div className="brand"><span className="brandmark">VA</span><div><b>Vitala Amanah</b><small>Your family organiser</small></div></div>
      <nav>{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>go(n.id)}><span aria-hidden>{n.icon}</span>{n.label}</button>)}</nav>
      <div className="sidebar-foot">{account?<><span className="demo-dot"/> Signed in<br/><small>{account.email}</small><button className="account-link" onClick={async()=>{await db.auth.signOut();setMenu(false);setNotice("You are signed out. The demo remains available.")}}>Sign out</button></>:<><span className="demo-dot"/> Demo workspace<br/><small>Fictional sample data</small><a className="account-link" href="/login">Sign in or create account</a></>}</div>
    </aside>
    {menu&&<button className="backdrop" aria-label="Close navigation" onClick={()=>setMenu(false)}/>}<main>
      <header><button className="hamburger" onClick={()=>setMenu(!menu)} aria-label={menu?"Close navigation":"Open navigation"} aria-expanded={menu}>☰</button><div className="mobile-brand">Vitala Amanah</div><div className="header-actions"><button className="text-button" onClick={()=>setNotice("Bahasa Melayu content is being prepared; English remains selected.")}>EN / BM</button>{account?<button className="avatar" aria-label="Account profile" title={account.email}>{account.email?.slice(0,2).toUpperCase()}</button>:<a className="header-login" href="/login">Sign in</a>}</div></header>
      <div className="content">{notice&&<div className="toast" role="status">✓ {notice}</div>}{error&&<div className="error"><b>Database setup needed</b><span>{error}</span></div>}{loading?<Loading/>:<>
        {view==="home"&&<Dashboard name={profile?.full_name||account?.email?.split("@")[0]||"there"} totals={totals} score={score} packProgress={packProgress} contacts={contacts} policies={policies} legacy={legacy} reminders={reminders} assets={assets} go={go} add={()=>setModal("asset")}/>}
        {view==="wealth"&&<Wealth assets={assets} liabilities={liabilities} totals={totals} add={setModal} remove={remove}/>} 
        {view==="protection"&&<Protection policies={policies} add={()=>setModal("policy")} remove={remove}/>} 
        {view==="legacy"&&<LegacyView records={legacy} add={()=>setModal("legacy")} remove={remove}/>} 
        {view==="retirement"&&<RetirementView profile={retirement} save={async(v)=>{await db.from("retirement_profiles").update(v).eq("id",retirement?.id);setNotice("Retirement assumptions updated.");await load()}}/>}
        {view==="family"&&<Family contacts={contacts} assets={assets} policies={policies} add={()=>setModal("contact")} remove={remove}/>} 
        {view==="familyPack"&&<FamilyPack record={familyPack} save={async draft=>{if(!account)return;const payload={owner_id:account.id,sections:draft.sections,completed_sections:draft.completed_sections,status:draft.completed_sections.length>=14?"ready":"draft"};const {error:e}=await db.from("family_packs").upsert(payload,{onConflict:"owner_id"});if(e){setNotice(`Could not save Family Pack: ${e.message}`);return}setNotice("Family Pack saved.");await load()}} preview={()=>window.print()}/>} 
        {view==="claims"&&<ClaimsCentre records={claims} save={save} remove={remove}/>}
        {view==="documents"&&<Documents records={documents} save={save} remove={remove}/>}
        {view==="professionals"&&<Professionals records={professionals} save={save} remove={remove}/>}
        {view==="guide"&&<VitalaGuide embedded facts={{score,assets:assets.length,liabilities:liabilities.length,policies:policies.length,trusted:contacts.filter(c=>c.emergency_access).length,legacy:legacy.length,packProgress,retirementAge:retirement?.retirement_age}}/>}
        {view==="reports"&&<ReportsCentre/>}
        {view==="reminders"&&<Reminders records={reminders} add={()=>setModal("reminder")} toggle={async(r)=>{await db.from("reminders").update({completed:!r.completed}).eq("id",r.id);await load()}} remove={remove}/>} 
        {view==="settings"&&<Settings/>}
      </>}</div>
    </main>{guideOpen&&<VitalaGuide facts={{score,assets:assets.length,liabilities:liabilities.length,policies:policies.length,trusted:contacts.filter(c=>c.emergency_access).length,legacy:legacy.length,packProgress,retirementAge:retirement?.retirement_age}} close={()=>setGuideOpen(false)}/>}<button className="guide-fab" onClick={()=>setGuideOpen(!guideOpen)} aria-expanded={guideOpen}>✧ Vitala Guide</button>{modal==="asset"?<PropertyModal close={()=>setModal(null)} save={save}/>:modal&&<RecordModal type={modal} close={()=>setModal(null)} save={save}/>}</div>
}

function Title({eyebrow,title,copy,action,label="Add record"}:{eyebrow:string;title:string;copy:string;action?:()=>void;label?:string}){return <div className="title-row"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action&&<button className="primary" onClick={action}>＋ {label}</button>}</div>}
function Loading(){return <div className="loading"><div/><div/><div/></div>}
function Dashboard({name,totals,score,packProgress,contacts,policies,legacy,reminders,assets,go,add}:{name:string;totals:{assets:number;debts:number;coverage:number};score:number;packProgress:number;contacts:Contact[];policies:Policy[];legacy:Legacy[];reminders:Reminder[];assets:Asset[];go:(v:View)=>void;add:()=>void}){const scoreItems=[['Wealth records',15,assets.length>0],['Liabilities',10,totals.debts>0],['Protection',15,policies.length>0],['Nominations',15,legacy.some(l=>/nomination/i.test(l.record_type)&&l.status!=="Needs review")],['Hibah and legacy',15,legacy.some(l=>/hibah|will|wasiat|trust/i.test(l.record_type)&&l.status!=="Needs review")],['Trusted contacts',10,contacts.some(c=>c.emergency_access)],['Family Pack',10,packProgress>=75],['Retirement plan',10,true]] as const;const missing=scoreItems.filter(x=>!x[2]).map(x=>x[0]);return <>
  <Title eyebrow={new Intl.DateTimeFormat("en-MY",{weekday:"long",day:"numeric",month:"long"}).format(new Date())} title={`Good morning, ${name}`} copy="Your family plan is taking shape. Here is the clearest next step."/>
  <section className="hero-card family-hook"><div><span className="eyebrow light">FAMILY READINESS</span><h2>If something happened to you today, would your family know what to do?</h2><p>Prepare one secure, practical family pack containing the contacts, protection information, responsibilities and instructions your family may need.</p><div className="pack-actions"><button className="champagne" onClick={()=>go("familyPack")}>Prepare My Family Pack</button><button className="secondary" onClick={()=>go("family")}>Preview What Family Will See</button><button className="secondary" onClick={()=>window.print()}>Download PDF</button><button className="secondary" onClick={()=>go("familyPack")}>Share Securely</button></div></div><details className="readiness-detail"><summary><div className="score-ring" style={{"--score":`${score*3.6}deg`} as React.CSSProperties}><span><b>{score}</b><small>Readiness</small></span></div></summary><div className="score-breakdown">{scoreItems.map(([label,points,done])=><p key={label}><span>{done?"✓":"○"} {label}</span><b>{done?points:0}/{points}</b></p>)}</div></details></section>
  <section className="panel readiness-grid"><div><small>Emergency Pack completion</small><b>{packProgress}%</b></div><div><small>Verified trusted contacts</small><b>{contacts.filter(c=>c.emergency_access).length}</b></div><div><small>Insurance/takaful summary</small><b>{policies.length?"Recorded":"Missing"}</b></div><div><small>Nomination status</small><b>{scoreItems[3][2]?"Recorded":"Needs review"}</b></div><div><small>Hibah/legacy status</small><b>{scoreItems[4][2]?"Recorded":"Needs review"}</b></div><div><small>Professional contact</small><b>{legacy.some(l=>l.professional)?"Recorded":"Missing"}</b></div><div><small>Missing information</small><b>{missing.length} areas</b></div><div><small>Next best step</small><b>{missing[0]||"Review your Family Pack"}</b></div></section>
  <div className="metrics"><Metric label="Estimated net worth" value={money(totals.assets-totals.debts)} note={`${assets.length} asset records`}/><Metric label="Total protection" value={money(totals.coverage)} note="User-recorded coverage"/><Metric label="Upcoming actions" value={String(reminders.filter(r=>!r.completed).length)} note="Reviews and renewals"/></div>
  <div className="two-col"><section className="panel"><div className="panel-head"><div><span className="eyebrow">YOUR WEALTH</span><h2>At a glance</h2></div><button className="link" onClick={()=>go("wealth")}>View wealth →</button></div><div className="bar"><span style={{width:`${totals.assets?Math.max(8,(totals.assets-totals.debts)/totals.assets*100):0}%`}}/></div><div className="split"><div><small>Assets</small><b>{money(totals.assets)}</b></div><div><small>Liabilities</small><b>{money(totals.debts)}</b></div></div></section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">IF SOMETHING HAPPENS</span><h2>Family readiness</h2></div></div><ul className="checklist"><li className="done">Emergency contact recorded</li><li className={totals.coverage?"done":""}>Policy summary available</li><li>Nomination needs review</li></ul><button className="secondary" onClick={()=>go("family")}>Preview emergency pack</button></section></div>
  <p className="disclaimer">Vitala Amanah organises information and provides educational estimates. It does not provide legal, financial, insurance, tax or inheritance advice.</p></>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <section className="metric"><small>{label}</small><strong>{value}</strong><span>{note}</span></section>}
function Wealth({assets,liabilities,totals,add,remove}:{assets:Asset[];liabilities:Liability[];totals:{assets:number;debts:number};add:(s:string)=>void;remove:(t:string,id:string)=>void}){const properties=assets.filter(a=>a.category?.toLowerCase()==="property");return <><Title eyebrow="MY WEALTH" title="Everything you own and owe" copy="Keep a current, practical record without storing full account numbers." action={()=>add("asset")}/><div className="metrics"><Metric label="Assets" value={money(totals.assets)} note={`${assets.length} records`}/><Metric label="Liabilities" value={money(totals.debts)} note={`${liabilities.length} records`}/><Metric label="Net worth" value={money(totals.assets-totals.debts)} note="Current estimate"/></div>{properties.map(a=><PropertyCard key={a.id} asset={a} remove={()=>remove("assets",a.id)}/>)}<RecordSection title="Other assets" action={()=>add("asset")} rows={assets.filter(a=>!properties.includes(a)).map(a=>({id:a.id,title:a.name,meta:`${a.category} · ${a.liquidity||"Not classified"}`,value:money(a.value)}))} remove={id=>remove("assets",id)}/><RecordSection title="Liabilities" action={()=>add("liability")} rows={liabilities.map(a=>({id:a.id,title:a.name,meta:`${a.category} · ${a.lender||"No lender"}`,value:money(a.balance)}))} remove={id=>remove("liabilities",id)}/></>}
function PropertyCard({asset:a,remove}:{asset:Asset;remove:()=>void}){const valid=a.tenancy_end&&new Date(a.tenancy_end+"T23:59:59")>=new Date();return <section className="panel property-card"><div className="panel-head"><div><span className="eyebrow">PROPERTY DETAILS</span><h2>{a.name}</h2><p>{[a.property_type,a.address,a.state].filter(Boolean).join(" · ")||"Location not recorded"}</p></div><strong>{money(a.value)}</strong></div><div className="property-grid"><div><small>Use</small><b>{a.occupancy||"Not recorded"}</b></div><div><small>Ownership</small><b>{a.ownership_percentage||100}%{a.joint_owner?` with ${a.joint_owner}`:""}</b></div><div><small>Monthly rent</small><b>{money(Number(a.rental_income||0))}</b></div><div><small>Rental managed by</small><b>{a.rental_manager||"Self-managed / not recorded"}</b><span>{a.rental_manager_contact}</span></div><div><small>Tenancy validity</small><b className={valid?"positive":"negative"}>{valid?`Valid until ${date(a.tenancy_end||null)}`:"Expired or not recorded"}</b><span>{a.tenancy_agreement_name||"No agreement metadata"}</span></div><div><small>Loan bank</small><b>{a.loan_provider||"No loan recorded"}</b></div><div><small>Outstanding loan</small><b>{money(Number(a.outstanding_loan||0))}</b></div><div><small>Monthly bank payment</small><b>{money(Number(a.monthly_instalment||0))}</b></div><div><small>Interest / maturity</small><b>{a.interest_rate?`${a.interest_rate}%`:"—"} · {date(a.loan_maturity||null)}</b></div><div><small>Title / tenure</small><b>{a.title_number||"Masked / not recorded"} · {a.tenure||"—"}</b></div></div><div className="property-actions"><button className="secondary" onClick={()=>alert("Editing is being added next; add a replacement record meanwhile.")}>Edit details</button><button className="delete-text" onClick={remove}>Delete property</button></div><p className="disclaimer">Document name and validity metadata only. Sensitive uploads remain disabled until encryption passes security review.</p></section>}
function Protection({policies,add,remove}:{policies:Policy[];add:()=>void;remove:(t:string,id:string)=>void}){return <><Title eyebrow="PROTECTION" title="Insurance & takaful" copy="Record coverage facts, renewals and the person your family should call." action={add} label="Add policy"/><RecordSection title="Policy register" action={add} rows={policies.map(p=>({id:p.id,title:`${p.provider} · ${p.policy_type}`,meta:`${p.masked_number||"Number not recorded"} · Renews ${date(p.renewal_date)}`,value:money(p.coverage)}))} remove={id=>remove("policies",id)}/><p className="disclaimer">Coverage summaries are based only on information you enter and are not a recommendation or assessment of adequacy.</p></>}
function LegacyView({records,add,remove}:{records:Legacy[];add:()=>void;remove:(t:string,id:string)=>void}){return <><Title eyebrow="LEGACY" title="Hibah, nominations & documents" copy="Keep each concept separate and know what still needs professional review." action={add}/><RecordSection title="Legacy register" action={add} rows={records.map(r=>({id:r.id,title:r.title,meta:`${r.record_type} · ${r.status} · Review ${date(r.review_date)}`,value:r.professional||"No professional"}))} remove={id=>remove("legacy_records",id)}/><p className="disclaimer">A recorded document or nomination is not confirmation of legal validity or beneficial ownership.</p></>}
function RecordSection({title,rows,action,remove}:{title:string;rows:{id:string;title:string;meta:string;value:string}[];action:()=>void;remove:(id:string)=>void}){return <section className="panel records"><div className="panel-head"><h2>{title}</h2><button className="secondary" onClick={action}>＋ Add</button></div>{rows.length?rows.map(r=><article className="record" key={r.id}><span className="record-icon">◆</span><div><b>{r.title}</b><small>{r.meta}</small></div><strong>{r.value}</strong><button className="delete" onClick={()=>remove(r.id)} aria-label={`Delete ${r.title}`}>×</button></article>):<div className="empty"><b>No records yet</b><span>Add the first one to make this section useful.</span><button className="primary" onClick={action}>Add record</button></div>}</section>}
function Family({contacts,assets,policies,add,remove}:{contacts:Contact[];assets:Asset[];policies:Policy[];add:()=>void;remove:(t:string,id:string)=>void}){const shared=contacts.filter(c=>c.emergency_access);return <><Title eyebrow="FAMILY" title="People & emergency pack" copy="Pre-authorise exactly what a trusted person may see—never your whole vault." action={add} label="Add contact"/><div className="two-col"><section className="panel"><div className="panel-head"><h2>Trusted people</h2></div>{contacts.map(c=><article className="record" key={c.id}><span className="avatar small">{c.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><div><b>{c.name}</b><small>{c.relationship} · {c.role}</small></div>{c.emergency_access&&<span className="pill">Pack access</span>}<button className="delete" onClick={()=>remove("contacts",c.id)}>×</button></article>)}</section><section className="pack"><span className="eyebrow light">RECIPIENT PREVIEW</span><h2>Family Emergency Pack</h2><p>Prepared for {shared[0]?.name||"no recipient yet"}</p><hr/><b>Included</b><ul><li>{contacts.length} trusted contact{contacts.length!==1?"s":""}</li><li>{policies.length} policy summary</li><li>Redacted summary of {assets.length} assets</li></ul><b>Always excluded</b><p>Passwords, PINs, full account numbers and source documents.</p><button className="champagne" onClick={()=>window.print()}>Print safe preview</button></section></div></>}
function Reminders({records,add,toggle,remove}:{records:Reminder[];add:()=>void;toggle:(r:Reminder)=>void;remove:(t:string,id:string)=>void}){return <><Title eyebrow="REMINDERS" title="Nothing important slips through" copy="Track renewals, expiries and regular family plan reviews." action={add}/><section className="panel records">{records.map(r=><article className="record" key={r.id}><button className={r.completed?"check checked":"check"} onClick={()=>toggle(r)} aria-label="Toggle complete">✓</button><div><b>{r.title}</b><small>{r.category} · {date(r.due_date)}</small></div><span className={r.completed?"pill":"pill amber"}>{r.completed?"Complete":"Upcoming"}</span><button className="delete" onClick={()=>remove("reminders",r.id)}>×</button></article>)}</section></>}
function RetirementView({profile,save}:{profile:Retirement|null;save:(v:Record<string,number>)=>void}){const [p,setP]=useState(profile);useEffect(()=>setP(profile),[profile]);if(!p)return <div className="empty">No profile</div>;const years=p.retirement_age-p.current_age,r=p.annual_return/1200,fv=Number(p.current_savings)*Math.pow(1+r,years*12)+Number(p.monthly_contribution)*((Math.pow(1+r,years*12)-1)/r);const need=Number(p.monthly_spending)*12*25*Math.pow(1+p.inflation/100,years);return <><Title eyebrow="RETIREMENT" title="A clearer path to later life" copy="Adjust assumptions and see an educational projection—not a guarantee."/><div className="two-col"><form className="panel form-grid" onSubmit={e=>{e.preventDefault();save(p as unknown as Record<string,number>)}}>{([["current_age","Current age"],["retirement_age","Retirement age"],["monthly_spending","Monthly spending (RM)"],["current_savings","Current savings (RM)"],["monthly_contribution","Monthly contribution (RM)"],["annual_return","Expected annual return (%)"],["inflation","Inflation (%)"]] as [keyof Retirement,string][]).map(([k,l])=><label key={k}>{l}<input type="number" value={p[k] as number} onChange={e=>setP({...p,[k]:Number(e.target.value)})}/></label>)}<button className="primary" type="submit">Save assumptions</button></form><section className="hero-card projection"><span className="eyebrow light">EXPECTED SCENARIO</span><h2>{money(fv)}</h2><p>Projected fund at age {p.retirement_age}</p><div className="projection-row"><span>Estimated fund needed</span><b>{money(need)}</b></div><div className="projection-row"><span>Projected {fv>=need?"surplus":"shortfall"}</span><b className={fv>=need?"positive":"negative"}>{money(Math.abs(fv-need))}</b></div><small>Method: monthly compounding with spending inflated to retirement, using a 25× annual-spending planning factor.</small></section></div><p className="disclaimer">Projections are estimates based on editable assumptions. Returns and inflation vary; consider qualified professional advice.</p></>}
function Settings(){return <><Title eyebrow="SETTINGS" title="Your preferences" copy="Accessibility and privacy controls stay easy to reach."/><section className="panel settings"><label><span><b>Larger text</b><small>Increase text throughout the app</small></span><input type="checkbox" onChange={e=>document.documentElement.classList.toggle("large-text",e.target.checked)}/></label><label><span><b>Dark mode</b><small>Use a lower-light colour scheme</small></span><input type="checkbox" onChange={e=>document.documentElement.classList.toggle("dark",e.target.checked)}/></label><label><span><b>Reduce motion</b><small>Minimise interface animation</small></span><input type="checkbox" onChange={e=>document.documentElement.classList.toggle("reduce-motion",e.target.checked)}/></label></section></>}
function RecordModal({type,close,save}:{type:string;close:()=>void;save:(t:string,v:Record<string,unknown>)=>void}){const configs:Record<string,{table:string;title:string;fields:[string,string,string?][]}>={asset:{table:"assets",title:"Add an asset",fields:[["name","Asset name"],["category","Category"],["value","Estimated value (RM)","number"],["institution","Institution / provider"]]},liability:{table:"liabilities",title:"Add a liability",fields:[["name","Liability name"],["category","Category"],["balance","Outstanding balance (RM)","number"],["lender","Lender"]]},policy:{table:"policies",title:"Add a policy",fields:[["provider","Insurer / takaful operator"],["policy_type","Policy type"],["masked_number","Masked number"],["coverage","Coverage amount (RM)","number"],["renewal_date","Renewal date","date"],["claims_contact","Claims contact"]]},contact:{table:"contacts",title:"Add a trusted person",fields:[["name","Full name"],["relationship","Relationship"],["role","Role"],["phone","Mobile number"],["email","Email","email"]]},legacy:{table:"legacy_records",title:"Add a legacy record",fields:[["title","Record title"],["record_type","Type"],["status","Status"],["professional","Professional / provider"],["review_date","Review date","date"]]},reminder:{table:"reminders",title:"Add a reminder",fields:[["title","Reminder"],["category","Category"],["due_date","Due date","date"]]}};const c=configs[type];function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data:Record<string,unknown>=Object.fromEntries(new FormData(e.currentTarget));c.fields.forEach(([n,,t])=>{if(t==="number")data[n]=Number(data[n])});if(type==="contact")data.emergency_access=true;save(c.table,data)}return <div className="modal-wrap" role="dialog" aria-modal="true"><form className="modal" onSubmit={submit}><div className="panel-head"><div><span className="eyebrow">NEW RECORD</span><h2>{c.title}</h2></div><button type="button" className="close" onClick={close}>×</button></div>{c.fields.map(([n,l,t])=><label key={n}>{l}<input name={n} type={t||"text"} required={!n.includes("professional")&&!n.includes("masked")&&!n.includes("contact")&&!n.includes("institution")} min={t==="number"?0:undefined}/></label>)}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" type="submit">Save record</button></div></form></div>}
