"use client";
import { FormEvent } from "react";
import { SelectField } from "./select-field";

export default function PropertyModal({close,save,initial}:{close:()=>void;save:(t:string,v:Record<string,unknown>)=>void;initial?:Record<string,unknown>}){
  const fields:[string,string,string?][]=[["name","Asset name"],["value","Current value (RM)","number"],["property_type","Property type"],["address","Full location / address"],["state","State"],["occupancy","Use"],["ownership_percentage","Ownership (%)","number"],["joint_owner","Joint owner"],["rental_income","Monthly rent received (RM)","number"],["rental_manager","Who manages the rental"],["rental_manager_contact","Rental manager contact"],["tenancy_start","Tenancy start","date"],["tenancy_end","Tenancy valid until","date"],["tenancy_agreement_name","Tenancy agreement filename"],["loan_provider","Loan bank"],["outstanding_loan","Outstanding loan (RM)","number"],["monthly_instalment","Monthly bank payment (RM)","number"],["interest_rate","Interest rate (%)","number"],["loan_maturity","Loan maturity","date"],["maintenance_fee","Monthly maintenance (RM)","number"],["title_number","Masked title number"],["tenure","Tenure"],["purchase_price","Purchase price (RM)","number"],["purchase_date","Purchase date","date"]];
  const choices:Record<string,string[]>={property_type:["Condominium","Apartment","Terrace house","Semi-detached","Bungalow","Commercial","Land"],state:["Johor","Kedah","Kelantan","Melaka","Negeri Sembilan","Pahang","Penang","Perak","Perlis","Sabah","Sarawak","Selangor","Terengganu","Kuala Lumpur","Labuan","Putrajaya"],occupancy:["Own stay","Rented","Vacant","Family use"],rental_manager:["Self-managed","Property agent","Family member","Tenant-managed"],tenure:["Freehold","Leasehold","Malay Reserved","Bumiputera lot"]};
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data:Record<string,unknown>=Object.fromEntries(new FormData(e.currentTarget));for(const [n,,t] of fields)if(t==="number")data[n]=Number(data[n]||0);data.category="Property";data.liquidity="Illiquid";data.tenancy_status=data.tenancy_end&&new Date(String(data.tenancy_end))>=new Date()?"Valid":"Not recorded";save("assets",data)}
  return <div className="modal-wrap" role="dialog" aria-modal="true"><form className="modal property-modal" onSubmit={submit}><div className="panel-head"><div><span className="eyebrow">PROPERTY RECORD</span><h2>{initial?"Edit property and financing":"Add property and financing"}</h2></div><button type="button" className="close" onClick={close}>×</button></div><p className="disclaimer">Record tenancy agreement details only. Sensitive uploads are disabled pending encryption review.</p>{fields.map(([n,l,t])=>choices[n]?<SelectField key={n} name={n} label={l} options={choices[n]} initial={String(initial?.[n]??"")} required={n==="occupancy"}/>:<label key={n}>{l}<input name={n} type={t||"text"} defaultValue={String(initial?.[n]??"")} required={["name","value","address"].includes(n)} min={t==="number"?0:undefined}/></label>)}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">{initial?"Save changes":"Save property"}</button></div></form></div>
}
