"use client";
import { useState } from "react";

const sections=[["owner","Owner identification summary"],["family","Spouse and dependants"],["contacts","Emergency and trusted contacts"],["protection","Insurance / takaful and claims contacts"],["assets","Asset summary"],["liabilities","Liabilities and monthly commitments"],["legacy","Nomination, hibah and legacy records"],["professionals","Professional contacts"],["documents","Document checklist and original locations"],["instructions","Owner instructions and immediate actions"]] as const;

export function ReportsCentre(){
  const [reportType,setReportType]=useState<"family-pack"|"professional-review">("family-pack"),[included,setIncluded]=useState<string[]>(sections.map(([id])=>id)),[redacted,setRedacted]=useState(true),[working,setWorking]=useState(false),[message,setMessage]=useState("");
  const toggle=(id:string)=>setIncluded(items=>items.includes(id)?items.filter(x=>x!==id):[...items,id]);
  async function generate(){setWorking(true);setMessage("");try{const response=await fetch("/api/reports/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reportType,includedSections:included,redacted})});if(!response.ok){const error=await response.json();throw new Error(error.error||"Report could not be generated.")}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`vitala-${reportType}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("Report generated and recorded in your audit history.")}catch(error){setMessage(error instanceof Error?error.message:"Report could not be generated.")}finally{setWorking(false)}}
  return <><div className="title-row"><div><span className="eyebrow">REPORTS CENTRE</span><h1>Prepare a clear, confidential pack</h1><p>Choose the report, preview every included section, and keep sensitive values masked by default.</p></div></div><div className="two-col report-layout"><section className="panel"><div className="report-types"><button className={reportType==="family-pack"?"selected":""} onClick={()=>setReportType("family-pack")}><b>Safe Emergency Family Pack</b><span>Practical information your family may need first.</span></button><button className={reportType==="professional-review"?"selected":""} onClick={()=>setReportType("professional-review")}><b>Estate & Professional Review Pack</b><span>A fuller register for discussion with qualified professionals.</span></button></div><h2>Include sections</h2><div className="section-picker">{sections.map(([id,label])=><label key={id}><input type="checkbox" checked={included.includes(id)} onChange={()=>toggle(id)}/><span>{label}</span></label>)}</div><label className="redaction-switch"><input type="checkbox" checked={redacted} onChange={e=>setRedacted(e.target.checked)}/><span><b>Mask sensitive values</b><small>Recommended. Full balances and identifiers are withheld.</small></span></label></section><section className="hero-card report-preview"><span className="eyebrow light">RECIPIENT PREVIEW</span><h2>{reportType==="family-pack"?"Safe Emergency Family Pack":"Estate & Professional Review Pack"}</h2><p>Confidential · Owner name and generation-date watermark · Unique report ID · Page numbers</p><ol>{sections.filter(([id])=>included.includes(id)).map(([,label])=><li key={label}>{label}</li>)}</ol><div className="preview-shield">{redacted?"✓ Sensitive values are masked":"⚠ Detailed values will be included deliberately"}</div><button className="champagne" disabled={working||included.length===0} onClick={generate}>{working?"Generating securely…":"Generate & Download PDF"}</button>{message&&<p className="report-message" role="status">{message}</p>}</section></div><p className="disclaimer">Reports use owner-recorded information and are educational organisation tools only. They do not claim legal validity. Passwords, PINs, card details and cryptographic secrets are always excluded.</p></>;
}
