"use client";
import { useState } from "react";

type GuideFacts={score:number;assets:number;liabilities:number;policies:number;trusted:number;legacy:number;packProgress:number;retirementAge?:number};
type Topic="score"|"missing"|"review"|"retirement"|"professional"|"concepts";
const topics:{id:Topic;en:string;bm:string}[]=[
  {id:"score",en:"Explain my readiness score",bm:"Terangkan skor kesediaan"},
  {id:"missing",en:"What information is missing?",bm:"Maklumat apa yang masih kurang?"},
  {id:"review",en:"Create annual review checklist",bm:"Cipta senarai semak tahunan"},
  {id:"retirement",en:"Review retirement assumptions",bm:"Semak andaian persaraan"},
  {id:"professional",en:"Questions for a professional",bm:"Soalan untuk pakar"},
  {id:"concepts",en:"Explain hibah and nomination",bm:"Terangkan hibah dan penamaan"},
];

export function VitalaGuide({facts,embedded=false,close}:{facts:GuideFacts;embedded?:boolean;close?:()=>void}){
  const [language,setLanguage]=useState<"en"|"bm">("en"),[answer,setAnswer]=useState("");
  function ask(topic:Topic){setAnswer(response(topic,facts,language))}
  return <section className={embedded?"guide-page":"guide-panel"} aria-label="Vitala Guide"><div className="panel-head"><div><span className="eyebrow">VITALA GUIDE · {language==="en"?"PRIVATE GUIDANCE":"PANDUAN PERIBADI"}</span><h2>{language==="en"?"How can I help?":"Bagaimana saya boleh membantu?"}</h2></div><div className="guide-controls"><button className="text-button" onClick={()=>setLanguage(language==="en"?"bm":"en")}>{language==="en"?"BM":"EN"}</button>{close&&<button className="close" onClick={close}>×</button>}</div></div><p className="guide-intro">{language==="en"?"Choose a question. Answers use only the record counts and planning facts shown in your workspace.":"Pilih soalan. Jawapan hanya menggunakan bilangan rekod dan fakta perancangan dalam ruang kerja anda."}</p><div className="guide-topics">{topics.map(t=><button key={t.id} onClick={()=>ask(t.id)}>{language==="en"?t.en:t.bm}</button>)}</div>{answer?<article className="guide-answer"><span className="eyebrow">{language==="en"?"GUIDANCE":"PANDUAN"}</span><div>{answer.split("\n").map((line,i)=><p key={i}>{line}</p>)}</div><button className="delete-text" onClick={()=>setAnswer("")}>{language==="en"?"Delete this answer":"Padam jawapan ini"}</button></article>:<div className="empty"><b>{language==="en"?"Your records stay private":"Rekod anda kekal peribadi"}</b><span>{language==="en"?"No documents, passwords or secret values are read or transmitted.":"Tiada dokumen, kata laluan atau nilai rahsia dibaca atau dihantar."}</span></div>}<p className="disclaimer">{language==="en"?"Educational guidance only. Confirm decisions with a qualified lawyer, licensed financial planner, tax professional or regulated adviser where appropriate.":"Panduan pendidikan sahaja. Sahkan keputusan dengan peguam, perancang kewangan berlesen, pakar cukai atau penasihat terkawal yang sesuai."}</p></section>
}
function response(topic:Topic,f:GuideFacts,bm:boolean|"en"|"bm") {const isBm=bm==="bm",missing=[!f.assets&&(isBm?"aset":"assets"),!f.liabilities&&(isBm?"liabiliti":"liabilities"),!f.policies&&(isBm?"perlindungan":"protection"),!f.trusted&&(isBm?"hubungan dipercayai":"trusted contacts"),!f.legacy&&(isBm?"rekod hibah/legasi":"hibah or legacy records"),f.packProgress<75&&(isBm?"Pek Keluarga":"Family Pack")].filter(Boolean).join(", ");
  if(topic==="score")return isBm?`Skor kesediaan anda ialah ${f.score}%. Ia berdasarkan kewujudan rekod kekayaan, liabiliti, perlindungan, penamaan, legasi, hubungan dipercayai, Pek Keluarga dan pelan persaraan. Skor ini tidak mengesahkan kesahan undang-undang.`:`Your readiness score is ${f.score}%. It reflects whether wealth, liabilities, protection, nominations, legacy, trusted contacts, Family Pack and retirement records exist. It does not validate legal effectiveness.`;
  if(topic==="missing")return missing?(isBm?`Keutamaan semasa: ${missing}. Mulakan dengan satu bahagian dan sahkan fakta dengan dokumen asal.`:`Current priorities: ${missing}. Start with one section and confirm facts against original documents.`):(isBm?"Bahagian utama telah direkodkan. Seterusnya, semak tarikh dan pengesahan profesional.":"The main sections are recorded. Next, review dates and professional confirmation.");
  if(topic==="review")return isBm?"Senarai tahunan: 1) Sahkan aset dan hutang. 2) Semak perlindungan dan penamaan. 3) Sahkan hubungan dipercayai. 4) Semak dokumen legasi. 5) Kemas kini andaian persaraan. 6) Jana semula Pek Keluarga.":"Annual checklist: 1) Confirm assets and debts. 2) Review protection and nominations. 3) Verify trusted contacts. 4) Review legacy documents. 5) Update retirement assumptions. 6) Regenerate the Family Pack.";
  if(topic==="retirement")return isBm?`Umur persaraan direkodkan: ${f.retirementAge||"belum ditetapkan"}. Uji inflasi, pulangan dan sumbangan menggunakan senario konservatif, jangkaan dan optimistik. Anggaran bukan jaminan.`:`Recorded retirement age: ${f.retirementAge||"not set"}. Test inflation, return and contribution assumptions under conservative, expected and optimistic scenarios. Projections are not guarantees.`;
  if(topic==="professional")return isBm?"Tanya: Dokumen mana perlu disemak? Adakah penamaan saya terkini? Siapa memiliki aset bersama? Apakah kekurangan dalam arahan keluarga saya? Apakah yuran dan skop nasihat anda?":"Ask: Which documents need review? Are my nominations current? How are jointly owned assets recorded? What is missing from my family instructions? What are your fees and scope of advice?";
  return isBm?"Hibah ialah konsep pemberian yang memerlukan fakta dan dokumentasi yang betul. Penamaan boleh membantu proses tuntutan atau pentadbiran, tetapi tidak semestinya menentukan pemilikan akhir. Dapatkan nasihat profesional untuk keadaan anda.":"Hibah is a gifting concept that depends on correct facts and documentation. A nomination may assist claims or administration but does not necessarily determine final ownership. Seek professional advice for your circumstances.";
}
