import Link from "next/link";

const features=[
  ["Wealth","Record property, savings, investments, businesses and liabilities in one practical register."],
  ["Protection","Organise insurance and takaful coverage, renewal dates, claims contacts and nomination facts."],
  ["Legacy","Keep hibah, nomination and legacy documents clearly separated with review reminders."],
  ["Family","Prepare a pre-authorised, redacted emergency pack without exposing the complete vault."],
  ["Retirement","Explore editable Malaysian retirement assumptions and understand possible shortfalls."],
  ["Documents","Track important document metadata and expiry dates while sensitive uploads remain disabled for review."]
];
const plans=[
  {name:"Free",price:"RM0",tag:"Individual",items:["10 structured records","No added family profiles","2 trusted contacts","Basic readiness dashboard"]},
  {name:"Pro",price:"RM19.90",tag:"Most popular",items:["Full planning and reports","1 managed family profile","Up to 10 trusted contacts","2 GB storage"]},
  {name:"Family",price:"RM39.90",tag:"Best for households",items:["2 private adult seats","Up to 5 managed dependants","Member workspace switcher","5 GB shared storage"]}
];

export default function PublicHome(){return <main className="public-site">
  <header className="public-header"><Link className="public-logo" href="/"><span>VA</span>Vitala Amanah</Link><nav><a href="#how">How it works</a><a href="#features">Features</a><a href="#security">Security</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><div className="public-actions"><Link className="text-link" href="/login">Sign In</Link><Link className="public-primary" href="/login?mode=signup">Start Free</Link></div></header>
  <section className="public-hero"><div><span className="public-kicker">YOUR LIFE, WEALTH AND LEGACY—ORGANISED SECURELY</span><h1>Give your family<br/><em>clarity, not questions.</em></h1><p>Vitala Amanah is a Malaysian-first command centre for organising wealth, protection, retirement and essential family information.</p><div className="hero-actions"><Link className="public-primary large" href="/login?mode=signup">Start Free</Link><Link className="public-secondary large" href="/login">Explore Demo</Link></div><small>No card required · Fictional demo workspace · English and Bahasa Melayu ready</small></div><div className="vault-visual" aria-label="Illustration of an organised family plan"><div className="vault-glow"/><article><span>Family readiness</span><strong>85</strong><small>Clear next steps</small></article><article><span>Estimated net worth</span><strong>RM697k</strong><small>Assets less liabilities</small></article><article><span>Emergency pack</span><strong>Ready</strong><small>Redacted by default</small></article></div></section>
  <section className="trust-strip"><span>Built for Malaysian families</span><span>Clear regulated disclaimers</span><span>Private-by-design roadmap</span><span>No secret-value storage</span></section>
  <section id="how" className="public-section"><div className="section-intro"><span className="public-kicker">HOW IT WORKS</span><h2>From scattered information to a family-ready plan</h2></div><div className="steps">{[["01","Record","Add assets, liabilities, policies and the people connected to them."],["02","Protect","Track renewals, missing information and documents requiring review."],["03","Share","Choose the exact redacted information a trusted person may access."],["04","Prepare","Keep an emergency pack and annual family review up to date."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  <section id="features" className="public-section tint"><div className="section-intro"><span className="public-kicker">ONE CALM FAMILY SYSTEM</span><h2>See what you own, what protects you and what still needs attention</h2></div><div className="feature-grid">{features.map(([title,copy])=><article key={title}><div className="feature-icon">◆</div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section id="security" className="security-section"><div><span className="public-kicker light">SECURITY & PRIVACY</span><h2>Trust starts with accurate claims.</h2><p>We use managed Supabase authentication, server-enforced sessions and database access rules. We do not claim zero-knowledge or end-to-end document encryption.</p><Link className="champagne-link" href="/login">Explore the safe demo</Link></div><ul><li><b>Public demo separation</b><span>Fictional records are clearly labelled and separated from real accounts.</span></li><li><b>Sensitive uploads disabled</b><span>Real document contents stay unavailable until client encryption passes independent review.</span></li><li><b>Redacted by default</b><span>Emergency packs and future reports exclude full identifiers and secrets.</span></li><li><b>Clear audit direction</b><span>High-risk access and sharing actions are designed to leave a reviewable history.</span></li></ul></section>
  <section id="pricing" className="public-section"><div className="section-intro"><span className="public-kicker">FOUNDING MEMBER PRICING</span><h2>Start free. Upgrade only when a paid benefit matters.</h2><p>Annual billing: Pro RM199 (save RM39.80, 16.7%); Family RM399 (save RM79.80, 16.7%).</p></div><div className="pricing-grid">{plans.map(p=><article key={p.name} className={p.name==="Pro"?"popular":""}><span className="plan-tag">{p.tag}</span><h3>{p.name}</h3><strong>{p.price}</strong><small>{p.name==="Free"?"forever":"per month"}</small><ul>{p.items.map(i=><li key={i}>✓ {i}</li>)}</ul><Link className={p.name==="Free"?"public-secondary":"public-primary"} href="/login?mode=signup">{p.name==="Free"?"Start Free":`Choose ${p.name}`}</Link></article>)}</div><p className="pricing-note">Payments are not charged until Stripe or ToyyibPay webhook verification is configured. Paid access is never granted from a browser return URL alone.</p></section>
  <section id="faq" className="public-section tint"><div className="section-intro"><span className="public-kicker">FREQUENTLY ASKED</span><h2>Practical answers before you begin</h2></div><div className="faq-grid">{[["Is Vitala Amanah a lawyer or financial adviser?","No. It organises your information and offers educational calculations and checklists. Seek qualified professional advice for legal, tax, financial and inheritance decisions."],["Can administrators read private documents?","Real document uploads are currently disabled. They will remain disabled until a reviewed client-encryption and recovery design can enforce the required privacy boundary."],["Is the demo real?","The account session and database are real; every person, balance and organisation shown in the demo is fictional."],["Does nomination decide ownership?","Not necessarily. The app keeps nomination, hibah, wills, trusts and distribution concepts separate and does not determine legal validity."],["Can I cancel a paid plan?","The planned paid service includes a 30-day grace period followed by read-only access. Existing data is not held hostage after downgrade."],["Where is my data hosted?","The current application uses Vercel and Supabase. Detailed retention, backup and residency disclosures must be completed before real sensitive-data launch."]].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  <section id="contact" className="contact-section"><div><span className="public-kicker">READY TO GET ORGANISED?</span><h2>Start with one record today.</h2><p>Explore fictional data first, or create an account for your own workspace.</p></div><div className="hero-actions"><Link className="public-primary large" href="/login?mode=signup">Start Free</Link><a className="public-secondary large" href="mailto:hello@vitala-amanah.app">Contact</a></div></section>
  <footer className="public-footer"><div><Link className="public-logo" href="/"><span>VA</span>Vitala Amanah</Link><p>Your life, wealth and legacy—organised securely.</p></div><div><b>Product</b><a href="#features">Features</a><a href="#security">Security</a><a href="#pricing">Pricing</a></div><div><b>Legal</b><a href="#faq">Privacy</a><a href="#faq">Terms</a><a href="#faq">AI Disclaimer</a><a href="#faq">Financial & Legal Disclaimer</a></div><div><b>Access</b><Link href="/login">Sign In</Link><Link href="/login">Explore Demo</Link><a href="mailto:hello@vitala-amanah.app">Contact</a></div><small>© 2026 Vitala Amanah. Organisational and educational platform only.</small></footer>
  </main>}
